import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
def least_squares(x, y):
    b = (np.mean(x*y)-np.mean(x)*np.mean(y))/(np.mean(x**2)-np.mean(x)**2)
    a = np.mean(y) - b*np.mean(x)
    return b, a
df = pd.read_csv("C:/Users/user/Downloads/iris_data.csv")
SW = np.array(df['SepalWidthCm'])
SL = np.array(df['SepalLengthCm'])
PW = np.array(df['PetalWidthCm'])
PL = np.array(df['PetalLengthCm'])
fig = plt.figure(figsize = (16,9))
ax1 = fig.add_subplot(231)
ax2 = fig.add_subplot(232)
ax3 = fig.add_subplot(233)
ax4 = fig.add_subplot(234)
ax5 = fig.add_subplot(235)
ax6 = fig.add_subplot(236)
ax1.plot(SW,SL,'k.')
ax2.plot(SW,PW,'r.')
ax3.plot(SW,PL,'b.')
ax4.plot(SL,PW,'g.')
ax5.plot(SL,PL,'c.')
ax6.plot(PW,PL,'m.')
ax1.set_xlabel('SW Axis')
ax2.set_xlabel('SW Axis')
ax3.set_xlabel('SW Axis')
ax4.set_xlabel('SL Axis')
ax5.set_xlabel('SL Axis')
ax6.set_xlabel('PW Axis')
ax1.set_ylabel('SL Axis')
ax2.set_ylabel('PW Axis')
ax3.set_ylabel('PL Axis')
ax4.set_ylabel('PW Axis')
ax5.set_ylabel('PL Axis')
ax6.set_ylabel('PL Axis')
kn, vp = least_squares(PW, PL)
print(kn, vp)
ax6.plot(PW, PW*kn+vp, 'k')
values = ['kn='+str(round(kn,3)), 'vp='+str(round(vp,3))]
legend_elements = [plt.Line2D([0], [0], marker='', color='w',markersize=0, label=f'{val}')for val in values]
plt.legend(handles=legend_elements, handlelength=0, handletextpad=0)
plt.savefig('Task_4_graph.png', dpi=500)
plt.show()
